### ISSUE TITLE
Specific targets for the tests

### ISSUE THREAD

**Issue by tleunen** [babel/babel-preset-env#164]
How do you set different targets for the tests?

I'm having a specific  "test" env in my babelrc files. But the preset keeps also using the default settings as well.

Is it possible all the settings gets merged together, instead of overridden? If that's the case, is there a way to override some? For my unit tests, I only require the node target, not the browsers.

**Comment by simonkberg** [comment]
Could you share your babel config?

[Any non-env specific options will be merged with environment specific ones](https://babeljs.io/docs/usage/babelrc/#env-option). If you want to avoid that you should only define non-env specific options when you want them to apply across all environments, and use environment specific options otherwise.

Example:
```json5
{
  "presets": [
    "stage-2" // included in all environments
  ],
  "env": {
    "production": { // production environment transforms
      "presets": [
        ["env", {
          "targets": {
            "node": "4",
            "browsers": "last 2 versions"
          }
        }]
      ],
    },
    "development": { // development environment transforms
      "presets": [
        ["env", {
          "targets": {
            "node": "current",
            "browsers": "last 1 chrome version"
          }
        }]
      ],
    },
    "test": { // test environment transforms
      "presets": [
        ["env", {
          "targets": {
            "node": "current"
          }
        }]
      ],
    }
  },
}
```

Then execute babel (directly or via build tools) with the appropriate `NODE_ENV`/`BABEL_ENV` environment variable:
```sh
$ NODE_ENV=development BABEL_ENV=test babel src -d test
$ BABEL_ENV=development babel src -d dev # default
$ NODE_ENV=production babel src -d dist
```
The default is "development" if omitted

**Comment by tleunen** [comment]
Yep I found out that everything is merged so I have to keep my browser config only in dev/prod.
Thanks!

**Comment by hzoo** [comment]
Hopefully this won't be as much of an issue later when we go with babelrc.js and/or remove env option

**Comment by mstaicu** [comment]
I have a similar issue, I try to use babel-preset-env in different environments and I can't get it to work. I also would like to specify certain plugins to be used in certain environments. I failed to accomplish this as well. Any hints?
