### ISSUE TITLE
Idea: `"targets": { "googlebot": true }`

### ISSUE THREAD

**Issue by lydell** [babel/babel-preset-env#272]
I just saw this on Twitter and got an idea:

https://twitter.com/ebidel/status/851830310413058048

> SPA SEO? Googlebot: has modern browser but lacks older features (localStorage, promises, ES6). Always use polyfills.
>
> https://www.youtube.com/watch?v=JlP5rBynK3E

Sorry if this is out of scope :)

**Comment by hzoo** [comment]
I made uglify earlier and we wanted to change it to "useSyntax" instead https://github.com/babel/babel-preset-env/issues/234 since it just meant only handle polyfills. 

Not sure what it means to support it because it's not in compat-table and we don't have a way of knowing what it does. It really just sounds like compile everything + polyfill everything so not sure what you would get with having this option? @ebidel

**Comment by xtuc** [comment]
Is this just an idea or your actual use case?

Would you use SSR to publish a googlebot version of your application? How would you separate the routes?

**Comment by lydell** [comment]
Just an idea.

I was not thinking of publishing a googlebot version.

**Comment by lydell** [comment]
Meh, I don’t think this is such a good idea after all.
