### ISSUE TITLE
two issues about babel-preset-env.

### ISSUE THREAD

**Issue by MOONLIGHTV** [babel/babel-preset-env#279]
There is an **entry.js**:
`import {foo} from './foo.js'` 

**## issue 1:**
Now my  .babelrc setting like this:
`{ "presets": [ ["env", { "targets": { "browsers": ["last 2 versions", "ie >= 8"] } } ] ]}

But if I add `"**modules":false**` to active the **tree-shaking** and then use **babel-node** compile **entry.js**-------babel-node entry.js , it will told me import is not avaliable:
![1](https://cloud.githubusercontent.com/assets/14039419/24958435/daef19f2-1fc1-11e7-983c-7b6551419078.png)

So, how can I use both  **tree-shaking**  and **import/export** ?

------------------------------------------------------------------------------------------------------------
**## issue 2:**
I add **require('../css/main.js')** to entry.js became this:
`require('../css/main.js');
 import {foo} from './foo.js
`
Then run the babel-------babel-node entry.js
**But it dosen't work and show me another Error:**
![2](https://cloud.githubusercontent.com/assets/14039419/24958751/04df6d38-1fc3-11e7-9c2a-e2b9ca8e0b65.png)
What's wrong with it? Every **css-selector** all throw this Error...

**Comment by hzoo** [comment]
This doesn't seem related to preset-env, it's about your use of import/export/require with webpack and node.

For 1, this is because if you do `modules: false` you are asking the bundler (like webpack) to compile import/export for you. But if you run `babel-node` then you'd be using node itself to handle import/export, which it currently doesn't do. If you need to have both, then you need to have 2 different configs for your browser js code and for your node js code.

For 2, that that is the same issue. You can't require css - you need to run webpack. "tree shaking" is from running webpack not babel-node.

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by MOONLIGHTV** [comment]
Thanks a lot for answered me.
So. the result is I can only choose one from the two ---**<use webpack to compile javascript>** or **<use babel-node to run javascript>**?
And also thanks for links to slack community and StackOverflow....but in StackOverflow, nobody talks to me,mayby because I'm new to there,I was invisible to them.

**Comment by hzoo** [comment]
node/babel-node is to run js on the server (it doesn't understand import/export yet). webpack is used to bundle javascript to send to the browser (it handles import/export/require)

**Comment by MOONLIGHTV** [comment]
But if I use this .babelrc setting(**babel-preset-env** plugin without add **modules:false**):
`{ "presets": [ ["env", { "targets": { "browsers": ["last 2 versions", "ie >= 8"] } } ] ]}`

babel-node can understand and compile import/export...I know this in StackOverflow:http://stackoverflow.com/questions/33604470/unexpected-token-import-in-nodejs5-and-babel?answertab=active#tab-top

**Comment by hzoo** [comment]
Yeah because by default it compiles import/export to commonjs. I was saying because you did modules: false it wasn't compiling it.

**Comment by MOONLIGHTV** [comment]
Ok,clear~you can close the issue and have a nice day.
