### ISSUE TITLE
Consider mdn/browser-compat-data as source of data

### ISSUE THREAD

**Issue by chicoxyzzy** [babel/babel-preset-env#354]
Mozilla created their own [compatibility data repo](https://github.com/mdn/browser-compat-data). It doesn't contain much data right now (actually there is almost no data 😄) but we can help if we'll prefer it over compat-table in future.

**Comment by hzoo** [comment]
Does this need to be an issue?

This is nice though cc @wbamberg dono if you know about this project. It uses https://github.com/kangax/compat-table as the data to power whether Babel should compile a specific syntax or not. It's probably the only tool that uses the compat-data for actual usage rather than for documentation/checking compat, so it's necessary that the data is up to date and accurate.

**Comment by ljharb** [comment]
Why would we prefer it over compat-table?

**Comment by chicoxyzzy** [comment]
No reason to prefer it over compat-table. This one was created to track evolution of alternative source of data.

**Comment by chicoxyzzy** [comment]
Also possibly we can cooperate with them to reuse data of each other or make it compatible-ish

**Comment by hzoo** [comment]
Was going to close since don't think we need this issue to track it?

**Comment by ljharb** [comment]
I think that if a better alternative exists, great - but that if the engines don't keep the existing compat-table updated, then they're not going to keep any other one updated either. 

@wpamberg, is there a reason that mozilla created its own repo instead of contributing to compat-table?

**Comment by wbamberg** [comment]
@hzoo , thanks for the pointer! MDN's compat data repo is indeed in early stages right now, except for [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions), which is pretty complete.

And we'd be very happy to cooperate with compat-table, if there's any scope for that. @Elchi3 is leading this project in Mozilla. 

> @wpamberg, is there a reason that mozilla created its own repo instead of contributing to compat-table?

This repo was originally created so we could display compat data for WebExtensions in various different ways on MDN. Since then, we are expanding it to represent data for the other open web technologies documented on MDN, including JS, CSS, HTTP, and WebAPIs. A lot of this data already exists, embedded in the pages, so a big part of the work is migrating it from there into a structured format. AFAIK compat-table is only for ECMAScript, so it's not clear to me how it would meet the need for the other web technologies.

**Comment by hzoo** [comment]
Ok and this project (well Babel in general) is focused on ECMAScript and only needs that data, will close for now

**Comment by ljharb** [comment]
@wbamberg @Elchi3 thanks, that makes perfect sense :-) if there's any data you have or need about language features, it'd be great to coordinate with compat-table, but indeed compat-table doesn't cover other web tech.
