### ISSUE TITLE
target.browsers ChromeAndroid ignored

### ISSUE THREAD

**Issue by pixelass** [babel/babel-preset-env#366]
I expect "ChromeAndroid" to be supported but it is simply ignored

```json
{
  "targets": {
    "browsers": [
        "ie 11",
        "last 2 chrome versions",
        "last 2 safari versions",
        "last 2 firefox versions",
        "last 2 edge versions",
        "last 2 ios versions",
        "last 2 chromeandroid versions"
      ]
    }
  }
}
```

```
{
  "chrome": "57",
  "edge": "14",
  "firefox": "52",
  "ie": "11",
  "ios": "10",
  "safari": "10"
}
```

**Comment by yavorsky** [comment]
chromeandroid is just chrome if we are talking about es6 support. [I've added mapping](https://github.com/babel/babel-preset-env/pull/367), so it will override chrome value if chromeandroid's version is lower. To prevent duplication and confusion we will still log it as a chrome, because it's functionally the same, except naming.

**Comment by pixelass** [comment]
makes sense. Thank you. Maybe adding a log would help. Otherwise issues like this might pop up.

`chromeandroid merged with chrome.`

Adding a note about this in the readme could also help.

**Comment by yavorsky** [comment]
@pixelass Good idea 👍
