### ISSUE TITLE
async function always be transformed , 

### ISSUE THREAD

**Issue by lili21** [babel/babel-preset-env#378]
![2017-07-21 10 25 49](https://user-images.githubusercontent.com/4456380/28446697-0477178a-6dff-11e7-8da9-819c32ff963e.png)

**Comment by existentialism** [comment]
@lili21 looks like a bug in the REPL, if you click the debug checkbox, notice there's no targets listed:

![image](https://user-images.githubusercontent.com/56288/28447104-6a96661c-6d94-11e7-997a-5e2dd1eee2a9.png)

I verified this locally:

```sh
babel-preset-env: `DEBUG` option

Using targets:
{
  "chrome": "56"
}

Modules transform: commonjs

Using plugins:
  syntax-trailing-function-commas {"chrome":"56"}
```

**Comment by lili21** [comment]
@existentialism Thanks.

**Comment by yavorsky** [comment]
The root of the problem is that we are using old preset-env (with old browserslit) version for REPL. So, chrome > 55 returns none, because 55 chrome is the last known version.
Currently I'm trying to make script to convert this repo directly to standalone versions and get rid of https://github.com/yavorsky/babel-preset-env-standalone. For now, we need to update last one every time we update the original repo.
