### ISSUE TITLE
Add blacklist for transform plugins

### ISSUE THREAD

**Issue by johnthecat** [babel/babel-preset-env#60]
Hi!
I've found some problem with usage of this preset.
My config looks like this:
```javascript
presets: [
    ['env', {
        targets: {
            ie: 11,
            chrome: 47, //Sputnik browser,
            firefox: 'last 2 versions'
        },
        loose: true
    }]
],
plugins: [
    'fast-async'
]
```
And it's doesn't work, because preset tries to transform async functions with `babel-plugin-transform-async-to-generator` instead of `fast-async`. 
It looks strange to me, I think, user should have ability to ignore some plugins.
In my opinion, it should look like this:
```javascript
presets: [
    ['env', {
        blacklist: ['babel-plugin-transform-async-to-generator']
    }]
]
```

**Comment by yavorsky** [comment]
Nice idea! If we already have a `whitelist` option, why we couldn't add `blacklist`?

Moreover, *babel-preset-env* is just a preset. It accepts most options that are common to other presets (loose, modules, etc). Maybe blacklist and whitelist options would be useful for other presets also?

cc @hzoo

**Comment by hzoo** [comment]
some background: presets didn't have options until recently since Sebastian didn't want it to be too complicated and it would just be an array of plugins. If you wanted to customize a preset you would just make a new one yourself. It seemed fine at the time.

It was when we were seeing lots of es2015-loose, es2015-modules, es2015-webpack, etc that it was useful for us to add preset options and then also add a loose/modules option to es2015. I guess we are being conservative in that we should determine whether it's really necessary instead of adding more and more features/options.

It's better to allow users to experiment and all that before we decide to just add stuff. But yes whitelist/blacklist both are interesting.

**Comment by johnthecat** [comment]
Hi, @hzoo ! 
About 'fast-async' : it makes collision with 'async-to-generator' and result code looks ugly. 
About blacklist: after researching source code I found that it's easy to add blacklist into options, I will make PR soon. Thank for fast response!

**Comment by hzoo** [comment]
Cool, I can add this as well @johnthecat.

@MatAtBread feel like I didn't see this plugin before! Is is the same as https://github.com/babel/kneden? @marten-de-vries made that and we added it to the babel org if anyone wanted to help maintain it since it's not complete in functionality yet. Sounds really cool though and maybe we can merge the projects?

**Comment by hzoo** [comment]
I'l just do this now @johnthecat, thanks for offering though

**Comment by MatAtBread** [comment]
@hzoo It's similar in concept to kneden, but a couple of years older and as far as I can tell (I'm not a kneden expert)and more mature (it does all JS constructs). The babel plugin works, and is reasonably popular (and therefore well exercised), but it's not my focus as it's basically a wrapper around https://github.com/MatAtBread/nodent which does all the work. Feel free to contribute/fork as you wish

**Comment by MatAtBread** [comment]
@hzoo There's a playground at http://nodent.mailed.me.uk where you can see the kind of transforms it does
